### ISSUE TITLE
Mehr Typen zur Auswahl

### ISSUE THREAD

**Issue by olien** [eaCe/strucdata#5]
- Breadcrumb
- FAQ
- Job Posting
- CreativeWork (gerade für uns wichtig :-))
- Place
- ...

**Comment by eaCe** [comment]
Zur Übersicht...

https://structured-data-for-wp.com/docs/article/how-many-schema-types-do-we-support/

**Comment by olien** [comment]
https://schema.org/docs/full.html

**Comment by eaCe** [comment]
Man muss es ja nicht übertreiben ;)

**Comment by olien** [comment]
:-) NEIN. Aber 
**CreativeWork** fänd ich schon gut
